name: base-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - numpy
  - matplotlib
  - scipy
  - pandas
  - octave_kernel
  - pyjanitor
  - node
  - boto
  - django
  - requests
  - nodejs=9
  - jupyterlab>=0.33
  - notebook
  - vega
  - seaborn
  - altair
  - vega_datasets
  - cartopy
  - geopandas
  - pip:
    - jupyterlab_latex
    - prettyprint
    - mechanize
    - mplleaflet

