name: base-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - dill
  - partd
  - scipy
  - zstd
  - zlib
  - zict
  - zeromq
  - yaml
  - sqlite
  - sympy
  - sip
  - tk
  - isort
  - html5lib
  - jupyter
