name: base-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy
  - zstd
  - zlib
  - zict
  - zeromq
  - yaml
  - xz
  - xlwt
  - xlwings
  - wheel
  - tornado
  - sqlite
  - sympy
  - sip
  - tk
  - isort
  - ipytkernel
  - ipython
  - html5lib
  - jupyter
  - libssh2
