name: base-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - scipy
  - zstd
  - zlib
  - zict
  - zeromq
  - yaml
  - sqlite
  - sympy
  - sip
  - tk
  - isort
  - ipython
  - html5lib
  - jupyter
  - octave_kernel
  - python=3.7
