name: base-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - scipy
  - pandas
  - octave_kernel
  - pyjanitor
  - node
  - boto
  - django
  - requests
  - pip:
    - bash_kernel
