name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - scipy
  - seaborn
  - appmode
  - jupyterlab>=0.35
  - pip:
      - jupyterlab_latex
